# -*- coding: utf-8 -*-
"""Tensor_Maths_involving constants.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KCoFGaPUIhmi6j6XBWPMfMWz0CmruLdM
"""

import tensorflow as tf

a = tf.constant([20, 30, 40], name = "a")
b = tf.constant([10, 20, 30], name = "b")

sum_of_a = tf.reduce_sum(a, name="sum_of_a")
prod_of_b = tf.reduce_prod(b, name="prod_of_b")

mean_tensors = tf.reduce_mean([sum_of_a, prod_of_b], name="mean_tensors")
mul_tensors = tf.multiply(sum_of_a, prod_of_b, name="mul_tensors")

with tf.Session() as sess:
	print("a: ", sess.run(a))
	print("b: ", sess.run(b))
	print("Sum(a): ", sess.run(sum_of_a))
	print("Prod(b): ", sess.run(prod_of_b))
	print("Mean(Sum(a), Prod(b)): ", sess.run(mean_tensors))
	print("Sum(a) * Prod(b): ", sess.run(mul_tensors))

train_writer = tbc.get_writer();
train_writer.add_graph(sess.graph)

train_writer.flush();
tbc.close()

