# -*- coding: utf-8 -*-
"""Tensor_Maths_involving_Variables.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C8PmvFUTpVEyS1KKY3zV2fKFeZTUjcHF
"""

import tensorflow as tf
!pip install -U tensorboardcolab
from tensorboardcolab import *
import shutil

shutil.rmtree('./Graph_Var', ignore_errors=True)
os.mkdir('./Graph_Var')
tf.reset_default_graph()
tbc=TensorBoardColab()

A = tf.Variable([5.0, 1.5], tf.float32, name = "A")
B = tf.Variable([8.0, 4.5], tf.float32, name = "B")
x = tf.placeholder(tf.float32, name = "x")
y = A*x+B

init = tf.global_variables_initializer()

with tf.Session() as sess:
  sess.run(init)
  print("The value of y =Ax+B is :", sess.run(y, feed_dict={x:[8, 20]}))

train_writer = tbc.get_writer();
train_writer.add_graph(sess.graph)

train_writer.flush();

#If don't want to initialize all the variables
init = tf.variables_initializer([A])
with tf.Session() as sess:
  sess.run(init)
  print("The value of y =Ax+B is :", sess.run(y, feed_dict={x:[8, 20]}))

#Update the value of variable
num1 = tf.Variable(5)
num2 = tf.Variable(4)
init = tf.global_variables_initializer()
computation = num1.assign(tf.add(num1,num2))
with tf.Session() as sess:
  sess.run(init)
  for i in range(10):
    print(sess.run(computation))
    print("New Value = ", sess.run(num2.assign_add(2)))

